<a href="https://colab.research.google.com/github/IrfanSulaiman08/NUMPY/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np #numerical python(np) short form of numpy.
# array collection of data  with same datatype(homogenious).
a=np.array([1,2,3,4])
a=np.array([1,2,3.0,4])
a=np.array([1,2,3,4,"a"])
a

array(['1', '2', '3', '4', 'a'], dtype='<U21')

In [ ]:
#slicing forword slicing and backword slicing
b=np.array([1,2,3,4,5])
#1,2
#print(b[0],b[1])
print(b[0:1])
#5,4
#print(b[-1],b[-2])
print(b[-1:-3:-1])
#4,5
#print(b[3],b[4])
print(b[3::])
#2,1
#print(b[-4],b[-5])
print(b[-4::-1])

[1]
[5 4]
[4 5]
[2 1]


In [ ]:
#dimension

a=np.array([0,1,2,3,4])
b=np.array([[[0,1],[3,5],[4,5]]])

a.ndim # dimension=1 vector
b.ndim # dimension=2 matrix
print(b)

[[[0 1]
  [3 5]
  [4 5]]]


In [ ]:
#create  a 2*2 matrix 2,3,4,5
a=np.array([[2,3],[4,5]])
print(a.ndim)# it is used for show then dimension
print(a)
print(a.shape)#matrix form that means 2*2 matrix .
print(a.size)# total number of elements in array list.

2
[[2 3]
 [4 5]]
(2, 2)
4


In [ ]:
#create a 2*3 matrix and print size,shape,dimension.
b=np.array([[1,2,3],[4,5,6]])
print(b)
print(b.size)
print(b.shape)
print(b.ndim)

[[1 2 3]
 [4 5 6]]
6
(2, 3)
2


In [ ]:
#create 4*2 matrix display its size,shape,dimension.

z=np.array([[1,2],[3,4],[5,6],[7,8]])
print(z.ndim)
print(z.size)
print(z.shape)

2
8
(4, 2)


In [ ]:
#create 4*4 matrix
x=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(x)
print(x.ndim)
print(x.shape)
print(x.size)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
2
(4, 4)
16


In [ ]:
print(x[0])
x[:,0]#for printing column.
#3
x[0,2]
#5
x[1,0]
#15,16
x[3,2:]#(:)for starting to end.
#[10,11
#14,15]
x[2:,1:3]

[1 2 3 4]


array([[10, 11],
       [14, 15]])

In [ ]:
#zero matirx
z=np.zeros([3,3,3],dtype=int)
z

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [ ]:
#one matrix
z=np.ones([3,3],dtype=int)
z

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
#create two 2*2 matrix
a=np.array([[2,3],[4,5]])
a.shape
b=np.array([[4,5],[6,7]])
b.shape
print(a)
print(b)

[[2 3]
 [4 5]]
[[4 5]
 [6 7]]


In [ ]:
#matrix addition
print(a+b)
#matrix subtarction
print(a-b)
#matrix multiplication
print(a*b)#this not matrix multiplication
print(a@b)#@ used for multiply in matrix row by column.this mtrix multiplication
print(a.dot(b))#also used for matrix multtiplication (first variable.dot(second variable))
#matrix division
print(a/b)

[[ 6  8]
 [10 12]]
[[-2 -2]
 [-2 -2]]
[[ 8 15]
 [24 35]]
[[26 31]
 [46 55]]
[[26 31]
 [46 55]]
[[0.5        0.6       ]
 [0.66666667 0.71428571]]


In [ ]:
#full matrix
z=np.full([3,3],7,dtype=int)
z

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [ ]:
#create 3*4 matrix with value 9 and datatype complex
a=np.full([3,4],9,dtype=complex)
a

array([[9.+0.j, 9.+0.j, 9.+0.j, 9.+0.j],
       [9.+0.j, 9.+0.j, 9.+0.j, 9.+0.j],
       [9.+0.j, 9.+0.j, 9.+0.j, 9.+0.j]])

In [ ]:
#identity matrix
z=np.identity(3,dtype=int)
z
z=np.eye(4,dtype=int)
z

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [ ]:
#create a 4*4 matrix
y=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(y)
print(y.size)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
16


In [ ]:
a=y.reshape(8,2)
a

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16]])

In [ ]:
#a range
a=np.arange(1,10,2)
a

array([1, 3, 5, 7, 9])

In [ ]:
#create a 5*2 matrix using arange
a=np.arange(1,11).reshape(5,2)
a

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
#create a 3*3 matrix with float values
a=np.array([[1.2,2.3,3.4],[4.5,5.6,6.7],[8.9,9.10,10.11]])
a

array([[ 1.2 ,  2.3 ,  3.4 ],
       [ 4.5 ,  5.6 ,  6.7 ],
       [ 8.9 ,  9.1 , 10.11]])

Here are some matrix sample questions using NumPy. Try to solve them by writing Python code in the cells below.

**Question 1:** Create a 3x3 identity matrix.

In [ ]:
# Write your code here to create a 3x3 identity matrix
z=np.identity(3,dtype=int)
print(z)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


**Question 2:** Create a 4x4 matrix filled with the value 5.

In [ ]:
# Write your code here to create a 4x4 matrix filled with 5
a=np.full([4,4],5,dtype=int)
a

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

**Question 3:** Create a 2x3 matrix with values ranging from 10 to 15 using `arange` and `reshape`.

In [ ]:
# Write your code here to create a 2x3 matrix using arange and reshape
b=np.arange(1,7).reshape(2,3)
b

array([[1, 2, 3],
       [4, 5, 6]])

**Question 4:** Given two matrices `A` and `B`, perform matrix addition and matrix multiplication.

In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Write your code here to perform matrix addition and multiplication of A and B
print(A@B)

[[19 22]
 [43 50]]


**Question 5:** Create a 3x3 matrix with random integer values between 0 and 10.

In [ ]:
# Write your code here
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**Question 6:** Given a matrix, extract the second row.

In [ ]:
# Write your code here
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix
matrix[1,:]
#matrix[1:2,0:]

array([4, 5, 6])

**Question 7:** Given a matrix, extract the third column.

In [ ]:
# Write your code here
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix[:,2])

[3 6 9]


**Question 8:** Given a matrix, transpose it.

In [ ]:
# Write your code here
matrix = np.array([[1, 2], [3, 4], [5, 6]])
transpose_matrix=matrix.T
print("orginal matrix is:",matrix)
print("transpose matrix id :",transpose_matrix)


orginal matrix is: [[1 2]
 [3 4]
 [5 6]]
transpose matrix id : [[1 3 5]
 [2 4 6]]


In [ ]:
#floor
z=np.floor(a)
z

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 8.,  9., 10.]])

In [ ]:
#ceil
z=np.ceil(a)
z

array([[ 2.,  3.,  4.],
       [ 5.,  6.,  7.],
       [ 9., 10., 11.]])

In [ ]:
#round (above .5 upper value.under .50 or.5 lower value)
z=np.round(a)
z

array([[ 1.,  2.,  3.],
       [ 4.,  6.,  7.],
       [ 9.,  9., 10.]])

In [ ]:
#create a 3*3 matrix
a=np.arange(1,10).reshape(3,3)
print(a)
a.max()
a.max(axis=1)#row(pandas opposite:-)
a.max(axis=0)#column(:-)
a.min(axis=1)
#a.min(axis=0)
a.sum(axis=1)
a.sum(axis=0)
#sqrt
s=np.sqrt(a)
s
#sin
si=np.sin(a)
si
#cos
c=np.cos(a)
#tan
t=np.tan(a)
t


[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[ 1.55740772, -2.18503986, -0.14254654],
       [ 1.15782128, -3.38051501, -0.29100619],
       [ 0.87144798, -6.79971146, -0.45231566]])

In [ ]:
#flatten:-convert to one dimentional
f=a.flatten()
f

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
#sort
#create 3*3 matrix
m=np.array([[2,3,3],[5,1,3],[7,8,7]])
print(m)
s=np.sort(m,axis=0)
s
s=np.sort(m,axis=1)
print(s)

#arg:-arg in numpy its working based on index.
#argsort
c=np.argsort(m,axis=1)
print(c)


[[2 3 3]
 [5 1 3]
 [7 8 7]]
[[2 3 3]
 [1 3 5]
 [7 7 8]]
[[0 1 2]
 [1 2 0]
 [0 2 1]]


In [ ]:
#numpy:
#1)np.Array:particular data convert into array
#2)size,shape,dimension(ndim),slicing,
#3)zero matrix,ones matrix,identitu matrix,full matrix(ull matrix is also known as ones matrix)
#4)additon,sub,mul(@),(a.dot(b))
#5)a range,reshape
#6)sum,min,max,axis=1(row),axis=0(column)
#7)round,ceil,floor
#8)sort,argsort
#9)flatten(convert into one dimensional array)